apiVersion: v1
kind: Pod
metadata:
  name: server3-pod
  annotations:
    appDescription: This pod is used to deploy nginx server
    author: Mahfudz AAAAAA XXXXXX
spec:
  containers:
    - name: nginx-server
      image: nginx:latest
      ports:
        - containerPort: 80
    - name: redis-db
      image: redis:latest
      ports:
        - containerPort: 6379
