apiVersion: v1
kind: Pod
metadata:
  name: server1-pod
spec:
  containers:
    - name: nginx-server
      image: nginx:latest
      ports:
        - containerPort: 80
    - name: redis-db
      image: redis:latest
      ports:
        - containerPort: 6379
