apiVersion: v1
kind: ReplicaSet
metadata:
  name: replica-set-pod
spec:
  replicas: 3
  selector:
    matchLabels:
      environment: production
  template:
    metadata:
      name: nginx-server
      lables:
        environment: production
    spec:
      containers:
        - name: nginx-server
          image: nginx:latest
          ports:
            - containerPort: 80
