apiVersion: v1
kind: ReplicationController
meta:
  name: contoller1
  labels:
    description: replication-controller-1
  annotations:
    longDescription: "Replication controller 1"
spec:
  replicas: 3 # pod amount
  selector:
    environment: production # pod label
  template:
    metadata:
      name: nginx-server
      labels:
        environment: production
    spec:
      containers:
        - name: nginx-container
          image: nginx:latest
          ports:
            - containerPort: 80
