apiVersion: v1
kind: DaemonSet
metadata:
  name: daemon-set-1
spec:
  selector:
    matchLabels:
      environment: production
  template:
    metadata:
      name: pod-1
      labels:
        environment: production
    spec:
      containers:
        - name: nginx-server-1
          image: nginx:latest
          ports:
            - containerPort: 80
